name: Deploy app to S3

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build and package app
      run: npm run make
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.S3_BUCKET_REGION }}
    - name: Deploy to production S3
      run: |
        aws s3 cp dist s3://${{ secrets.S3_BUCKET }}/dist --recursive --exclude "*" --include "*.AppImage" --include "*.dmg" --include "*.zip"